#
# Kbuild file for ipconfig
#

static-y := static/ipconfig
shared-y := shared/ipconfig

# common .o files
objs := main.o netdev.o packet.o
# dhcp
objs += dhcp_proto.o
# bootp
objs += bootp_proto.o


# TODO - do we want a stripped version
# TODO - do we want the static.g + shared.g directories?


# Create built-in.o with all object files (used by kinit)
lib-y := $(objs)

# .o files used to built executables
static/ipconfig-y := $(objs)
shared/ipconfig-y := $(objs)

ifeq (a,b)
# TODO - can we replace this with built-in.o?
$(LIB): $(OBJS)
	$(AR) cru $(LIB) $(OBJS)

install: all
	$(INSTALL_EXEC) shared/* $(INSTALLROOT)$(INSTALLDIR)/$(CROSS)bin

endif
