#
# Kbuild file for kinit/zlib
#

# common .o files
objs := adler32.o crc32.o infback.o inffast.o \
	inftrees.o inflate.o zutil.o

# zlib config flags
KLIBCCFLAGS += -DDYNAMIC_CRC_TABLE -DNO_GZCOMPRESS

# Create built-in.o with all object files
lib-y := $(objs)
