#
# Build klcc
#

always := $(KLIBCCROSS)klcc

$(obj)/$(KLIBCCROSS)klibc.config: $(src)/Kbuild \
				  $(srctree)/Makefile \
                                  $(srctree)/scripts/Kbuild.klibc
	rm -f $@
	echo 'ARCH=$(ARCH)' >> $@
	echo 'CROSS=$(KLIBCCROSS)' >> $@
	echo 'KCROSS=$(KCROSS)' >> $@
	echo 'CC=$(KLIBCCC)' >> $@
	echo 'LD=$(KLIBCLD)' >> $@
	echo 'REQFLAGS=$(filter-out -I%,$(KLIBCREQFLAGS))' >> $@
	echo 'OPTFLAGS=$(KLIBCOPTFLAGS)' >> $@
	echo 'LDFLAGS=$(KLIBCLDFLAGS)' >> $@
	echo 'STRIP=$(KLIBCSTRIP)' >> $@
	echo 'STRIPFLAGS=$(KLIBCSTRIPFLAGS)' >> $@
	echo 'EMAIN=$(KLIBCEMAIN)' >> $@
	echo 'BITSIZE=$(KLIBCBITSIZE)' >> $@
	echo 'prefix=$(INSTALLDIR)' >> $@
	echo 'bindir=$(INSTALLDIR)/$(KCROSS)bin' >> $@
	echo 'libdir=$(INSTALLDIR)/$(KCROSS)lib' >> $@
	echo 'includedir=$(INSTALLDIR)/$(KCROSS)include' >> $@

$(obj)/$(KLIBCCROSS)klcc: $(src)/makeklcc.pl $(src)/klcc.in \
                          $(obj)/$(KLIBCCROSS)klibc.config
	$(PERL) $< $(srctree)/$(src)/klcc.in $(obj)/$(KLIBCCROSS)klibc.config \
		$(shell bash -c 'type -p $(PERL)') > $@ || ( rm -f $@ ; exit 1 )
	chmod a+x $@
