#
# Kbuild file for gzip
#

# The gzip executable
user-progs := gzip
gzip-y     := gzip.o util.o unzip.o inflate.o

# Additional targets 
always := gunzip zcat gzip.stripped

# Optional ZIP support
gzip-$(CONFIG_KLIB_ZIP)   += zip.o deflate.o trees.o bits.o
cflags-$(CONFIG_KLIB_ZIP) += -DSUPPORT_ZIP
EXTRA_USERCFLAGS := $(cflags-y)

# Additionally linked targets
$(obj)/gunzip $(obj)/zcat: $(obj)/gzip
	$(call cmd,ln)

# A stripped version of gzip
$(obj)/gzip.stripped: $(obj)/gzip
	$(call cmd,strip)


# Old install target - TODO
#install: all
#	$(INSTALL_EXEC) gzip gunzip zcat $(INSTALLROOT)$(INSTALLDIR)/$(CROSS)bin
