
user-progs := gzip
gzip-y    := gzip.o util.o unzip.o inflate.o

ifeq (a,b)

Kept for convinience
ZIPSRCS = zip.c deflate.c trees.c bits.c
UNZIPSRCS = unzip.c inflate.c

SRCS = gzip.c util.c $(UNZIPSRCS)
OBJS = $(SRCS:.c=.o)
HDRS = gzip.h tailor.h revision.h
LIBS = $(KLIBC) $(LIBGCC)

ifeq ($(ZIP),y)
DEFS += -DSUPPORT_ZIP
SRCS += $(ZIPSRCS)
endif

all:	gzip gunzip zcat gzip.stripped

# Actual build-related targets

gzip:	Makefile $(OBJS) $(CRT0) $(LIBS)
	$(LD) $(LDFLAGS) -o $@ $(CRT0) $(OBJS) $(LIBS)

gunzip:	gzip
	rm -f $@
	ln $< $@

zcat: gzip
	rm -f $@
	ln $< $@

gzip.stripped: gzip
	$(STRIP) $< -o $@

clean:
	$(RM) -f core *.o gzip gunzip zcat gzip.stripped .*.d

spotless: clean
	rm -f *~

# These should presumably be shared...
install: all
	$(INSTALL_EXEC) gzip gunzip zcat $(INSTALLROOT)$(INSTALLDIR)/$(CROSS)bin
	
endif
