#
# Kbuild file for gzip
#

# The gzip executable
static-y := gzip
gzip-y   := gzip.o util.o unzip.o inflate.o

# Additional targets 
always := gunzip zcat gzip.stripped

# Optional ZIP support
gzip-$(CONFIG_KLIB_ZIP)   += zip.o deflate.o trees.o bits.o
cflags-$(CONFIG_KLIB_ZIP) += -DSUPPORT_ZIP
EXTRA_KLIBCCFLAGS := $(cflags-y)

# Additionally linked targets
$(obj)/gunzip $(obj)/zcat: $(obj)/gzip
	$(call cmd,ln)

# A stripped version of gzip
$(obj)/gzip.stripped: $(obj)/gzip
	$(call cmd,strip)

# Cleaning
targets := $(static-y) $(shared-y)

# Targets to install
install-y := gzip gunzip zcat
