#
# Kbuild file for kinit
#

static-y := kinit
kinit-y  := kinit.o do_mounts.o nfsroot.o getintfile.o initrd.o
kinit-y  += open.o readfile.o run-init/runinitlib.o

kinit-y  += ipconfig/
kinit-y  += nfsmount/
kinit-y  += run-init/

# Additional include paths files
KLIBCCFLAGS_kinit.o   := -I$(srctree)/$(src)/ipconfig \
			 -I$(srctree)/$(src)/run-init
KLIBCCFLAGS_nfsroot.o := -I$(srctree)/$(src)/ipconfig \
			 -I$(srctree)/$(src)/nfsmount

# Cleaning
targets := kinit kinit.g
subdir- := ipconfig nfsmount run-init


# install binary
install-y := kinit
