#
# Kbuild file for kinit
#

static-y := kinit
kinit-y  := kinit.o do_mounts.o getintfile.o initrd.o open.o readfile.o xpio.o
kinit-y  += do_mounts_md.o do_mounts_mtd.o nfsroot.o resume.o ramdisk_load.o

kinit-y  += ipconfig/
kinit-y  += nfsmount/
kinit-y  += run-init/
kinit-y  += fstype/
kinit-y  += zlib/

# Additional include paths files
KLIBCCFLAGS += -I$(srctree)/$(src)/ipconfig \
  	       -I$(srctree)/$(src)/nfsmount \
 	       -I$(srctree)/$(src)/run-init \
 	       -I$(srctree)/$(src)/fstype \
 	       -I$(srctree)/$(src)/zlib

# Cleaning
targets := kinit kinit.g
subdir- := ipconfig nfsmount run-init fstype zlib


# install binary
install-y := kinit
